use actual
brow
dele for unidad="GOB" OR UNIDAD="FFALE" or unidad="GII" or unidad="HOLAN" or unidad="MAFP" or unidad="ORF" or unidad="OTSER" or unidad="PL480" or unidad="SISCO" or unidad="WWF" or unidad="DINA" or unidad="MLUCA" or unidad="ACA"
brow
use resp
dele for unidad="GOB" OR UNIDAD="FFALE" or unidad="GII" or unidad="HOLAN" or unidad="MAFP" or unidad="ORF" or unidad="OTSER" or unidad="PL480" or unidad="SISCO" or unidad="WWF" or unidad="DINA" or unidad="MLUCA" or unidad="ACA"
use trasfe
dele for unidad="GOB" OR UNIDAD="FFALE" or unidad="GII" or unidad="HOLAN" or unidad="MAFP" or unidad="ORF" or unidad="OTSER" or unidad="PL480" or unidad="SISCO" or unidad="WWF" or unidad="DINA" or unidad="MLUCA" or unidad="ACA"
use oficina
dele for unidad="GOB" OR UNIDAD="FFALE" or unidad="GII" or unidad="HOLAN" or unidad="MAFP" or unidad="ORF" or unidad="OTSER" or unidad="PL480" or unidad="SISCO" or unidad="WWF" or unidad="DINA" or unidad="MLUCA" or unidad="ACA"
use bajas
dele for unidad="GOB" OR UNIDAD="FFALE" or unidad="GII" or unidad="HOLAN" or unidad="MAFP" or unidad="ORF" or unidad="OTSER" or unidad="PL480" or unidad="SISCO" or unidad="WWF" or unidad="DINA" or unidad="MLUCA" or unidad="ACA"
